### ISSUE TITLE
Clicking 'settings' on popup does nothing

### ISSUE THREAD

**Issue by kneutron** [polcak/jsrestrictor#123] opened 2021-10-04 13:54 UTC
OS: OSX High Sierra 10.13, 
Browser: latest Chrome 94.0.4606.71 (Official Build)

Frequent popups are annoying and I can find no way to turn them off, would rather have the plugin log things silently. Mouse hover over the Network Boundary Shield popup reveals a Settings button that does nothing when clicked

**Comment by polcak** [comment] 2021-10-05 11:30
I am not sure what the issue is:

* Is it that the settings button in pop up does not work?
* Is it that you do not want to see a pop up when you click on the JSR icon?
* Is it that you see Network Boundary Shield notifications?
* Is this a duplicate of #114?

**Comment by kneutron** [comment] 2021-10-05 14:12
Settings does nothing when clicked in the popup button, and notifications are too frequent / too large and distracting

**Comment by kneutron** [comment] 2021-10-06 13:22
DNS is 9.9.9.9, 8.8.8.8 and a local VM running Pihole 

> So you open pop up, click on the cogwheel and nothing happens?

Hover over the popup and "Settings" button appears in the lower right but does nothing when clicked on

**Comment by polcak** [comment] 2022-02-03 15:39
This issue is unclear and likely a duplicate of #125 Please let me know if I am wrong.

**Closed by polcak** 2022-02-03 15:39 UTC
Labels: duplicate, question
