### ISSUE TITLE
Shifted/Randomized ArrayBuffer does not work with Geolocation 

### ISSUE THREAD

**Issue by whatbh** [polcak/jsrestrictor#173] opened 2022-02-25 08:30 UTC
If ArrayBuffer is set to Shift or Randomize, the location service does not work at all. 
Tested on https://polcak.github.io/jsrestrictor/test/test.html, clicking "Show GPS data", error "Crypto.getRandomValues" is displayed in console.
<img width="709" alt="Screen Shot 2022-02-25 at 3 14 01 PM" src="https://user-images.githubusercontent.com/91888303/155681125-a94a8743-e9bc-4f55-b47e-4efd22ec7e79.png">
Is this behavior expected? If ArrayBuffer spoofing is expected to not work with Geolocation, it should be visibly indicated in the Setting so users can consider using this. If this is an error please look into this. 
Specs: Firefox 99 Nightly, JShelter 0.7.

**Comment by polcak** [comment] 2022-02-25 09:08
Yes, array buffers are known to break other APIs like Crypto and AudioBuffer. That is why they are now separated to an experimental level.

Duplicate of #164

**Closed by polcak** 2022-02-25 09:08 UTC

**Comment by polcak** [comment] 2022-02-25 15:24
Also relevant in this context https://pagure.io/JShelter/webextension/c/b02397295a9568efc14b29a84881ccdd678cecd5?branch=develgpsfarbling

This should land in the next bugfix release.
