### ISSUE TITLE
Broken sites from WebWorker protection on Firefox

### ISSUE THREAD

**Issue by brochard** [polcak/jsrestrictor#195] opened 2023-03-27 14:41 UTC
## Summary

I realised most broken sites I have is caused by the WebWorker protection so I gathered a list here and the level at which it works with no problem.

## Setup

Pages affected:

- Cryptpad (https://cryptpad.fr/drive/), works when WebWorker is set to Medium
- Twitch video player (https://www.twitch.tv/) // Unprotected
- Proton Mail/Calendar/Drive (https://mail.proton.me/ + https://calendar.proton.me/ + https://drive.proton.me/) // Unprotected
- Element (https://app.element.io/) works very slowly on Medium, works well on Unprotected
- Recaptcha sites (examples https://www.omgserv.com/fr/connexion/ + https://patrickhlauke.github.io/recaptcha/) // Unprotected
- Overleaf compiling to pdf (https://www.overleaf.com/) // Unprotected
- Gitlab difs (not on main instance, for example https://gitlab.redox-os.org/redox-os/presentations/-/merge_requests/1/diffs) // Unprotected

JShelter Version: 0.11.2

Popup information (open JShelter popup on affected pages:

JavaScript Shield ON
Network Boundary Shield ON
Fingerprint Detector ON
Level: Recommanded

[Optional:]

OS: Windows 10
Browser: Firefox
Other extensions that might affect JShelter behaviour: Ublock Origin

## How to reproduce

1. Open site
2. For overleaf only : connect to an account, create a document and see if it compiles on the right

## Expected result

Site loading / Videos loading / pdf compiling / Captcha completing

## Actual result

not loading

## Reproducibility

Tested it with another clean Firefox Nightly and Brave

-> They're all broken on both instance of Firefox
-> None of those sites are broken one Brave

## Workarounds

I gave the necessary WebWorker level for each of these

**Comment by polcak** [comment] 2023-04-03 17:10
Thank you. I added a link to this issue to https://pagure.io/JShelter/webextension/issue/80. I will close this one as a duplicate of the Pagure issue. If you have further comments, feel free to post here.

As posted in #199, I am not sure that we will try to fix this in MV2, we will try for MV3.

**Closed by polcak** 2023-04-03 17:10 UTC

**Comment by brochard** [comment] 2023-04-19 14:45
Thank you for keeping us updated @polcak
