### ISSUE TITLE
Popup is too small to use

### ISSUE THREAD

**Issue by airways** [polcak/jsrestrictor#127] opened 2021-10-04 19:25 UTC
The size of the popup window in Chrome appears to be too smol to use it:

![image](https://user-images.githubusercontent.com/64338/135911875-bdc15772-8351-4bae-b818-48c0b956347c.png)

Issue seen in these Chrome versions on Windows 10:
Version 94.0.4606.61 (Official Build) (64-bit)
Version 94.0.4606.71 (Official Build) (64-bit)

**Comment by TechnologyClassroom** [comment] 2021-10-04 19:37
Duplicate of https://github.com/polcak/jsrestrictor/issues/112

**Closed** 2021-10-05 11:37 UTC
Labels: duplicate
