### ISSUE TITLE
Latest release makes Google Maps extremely slow and unresponsive

### ISSUE THREAD

**Issue by bertvandepoel** [polcak/jsrestrictor#179] opened 2022-03-17 18:40 UTC
I see that some large changes have been made to the extension. I find the UX quite a bit more complicated, but I see why it was done while reading through other issues.

I've noticed that with default settings, Google Maps is now impossible to use. It's extremely slow and often becomes unresponsive. I'm not quite sure if my only option is to disable the JS shield, or what is advised.

I understand that this behaviour is intended and means that things are working. However, I do wonder if it doesn't make the addon a bit difficult for less techy people to use. Ideally it should be relatively accessible to those who care about privacy without a lot of technical ability too.

**Comment by polcak** [comment] 2022-03-20 12:26
I tried OpenStreetMap.org and the performance is the same with the extension and without the extension. The canvas wrappers are not triggered at all.

Please, provide more details:
* What JavaScript Shield groups are triggered? (If you open popup, modify JavaScript Shield, detail tweaks, what groups have non-zero number of calls?)
* What likelihood does Fingerprint Detector (FPD) report in the popup? If you click on the FPD likelihood in the popup, you should see a window like https://pagure.io/JShelter/webextension/raw/main/f/logos_images/store_imgs/firefox5.png, can you provide a copy?

My primary advise is to stop using Google products. I see that you are from EU. Google services are illegal in EU. See, for example, https://noyb.eu/en/edps-sanctions-parliament-over-eu-us-data-transfers-google-and-stripe, https://noyb.eu/en/austrian-dsb-eu-us-data-transfers-google-analytics-illegal, https://www.cnil.fr/en/cookies-cnil-fines-google-total-150-million-euros-and-facebook-60-million-euros-non-compliance, https://noyb.eu/en/update-cnil-decides-eu-us-data-transfer-google-analytics-illegal, https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html, and others. You have no privacy with Google.

If you insist on keeping using the service that you think is broken by JShelter, you might want to first decide what is your goal in using JShelter. Is it because you do not want to be fingerprinted? If so, is FPD detecting that the service you are visiting detecting high likelihood of fingerprinting? If it is not and you are comfortable with the service, it makes sense to tweak the protection for the visited domain, and deactivate fingerprinting  wrappers. You can go through all the wrappers and turn off those with high number of calls. To simplify the task I added a new level that will be available in a future release https://pagure.io/JShelter/webextension/c/a6b94bd8c691eed42430ff2ed89c6e65c5e8af5b?branch=githubissue179 (probably 0.8.1).

**Comment by bertvandepoel** [comment] 2022-03-21 21:25
I would very much like to use a different service than Google Maps. Sadly, since I live in Brussels where I use public transport offered by 4 different providers (metro, tram, bus, train offered by MIVB, De Lijn, TEC and SNCB) as well as my bike, it's sadly not possible to use any OSM based alternatives. They simply do not have proper support for these kinds of mixed source public transport situations (even general public transport support is quite bad here). 

I'm very much aware of all the problems with with Google products, including the work by NOYB. This is why I selfhost quite a lot of things. Sadly, there currently is no working alternative to Google Maps, as outlined in talks by Karen Sandler and Bradley M. Kuhn from the Software Freedom Conservancy. 

My main concern with this issue is however that it used to work before and now it doesn't without there being much clear communication to the user why. This makes it difficult for less technical people to even know how to deal with this.

**Comment by polcak** [comment] 2022-04-22 09:47
I tried and have a couple of observations:

* Google maps trigger "Locally rendered images", "Graphic card information", and "Time precision" wrappers only.
* Google maps seems to use one of the wrapped calls to generate labels (like town names) and photos.
* When switched to strict level, the labels and photos become black squares. This make sense because JShelter returns empty array for 3D Canvas.
* The maps UI is a little bit slower on Recommended level. Once I managed to do something that made the page unresponsive (I zoomed out and the map was not filled).
* The maps UI feels like having the same speed with the "Turn fingerprinting protection off" level as without JShelter.

Unless I have some guidance how to reproduce "extremely slow" and "unresponsive", I do not see much that we can do. Unless we make default canvas wrappers more fragile and  the protection reversible.

Maybe you can elaborate on "My main concern with this issue is however that it used to work before and now it doesn't without there being much clear communication to the user why. This makes it difficult for less technical people to even know how to deal with this." Do you have any ideas what else we can do?

**Comment by polcak** [comment] 2023-09-22 09:25
I am testing 0.15.2 in Firefox 118 beta with optimizations in the wrappers, see https://jshelter.org/optimizations/. Google Maps seem to work just fine. I am using Recommended and I can move the map without any noticeable slowness. However, there is a missing functionality like getting details about objects in the map, incomplete UI etc. This can be fixed by setting WebWorkers to Remove.

I internally proposed to change the setting at https://lists.nongnu.org/archive/html/js-shield/2023-09/msg00013.html. Depending on our decision we might make Recommended level completely compatible with Google Maps.

**Closed by polcak** 2023-09-22 09:25 UTC
Labels: question, NLNet project evaluation phase

**Comment by polcak** [comment] 2023-09-22 09:55
Actually, Google Maps work in Chrome with Recommended just fine.

It seems to me that the issue in Firefox is the same as in https://pagure.io/JShelter/webextension/issue/80#comment-852202.
