### ISSUE TITLE
Edge issue

### ISSUE THREAD

**Issue by darek991** [polcak/jsrestrictor#122] opened 2021-10-04 13:50 UTC
Clicking on the extension icon displays a broken box. Currently running Edge stable, last version.

**Comment by TechnologyClassroom** [comment] 2021-10-04 16:06
Duplicate of https://github.com/polcak/jsrestrictor/issues/112

Can you provide some more details?  What is your browser version, operating system, and operating system version?

**Closed** 2021-10-05 11:26 UTC
Labels: duplicate
