### ISSUE TITLE
The notifications switch not working properly.

### ISSUE THREAD

**Issue by HUMORCE** [polcak/jsrestrictor#185] opened 2022-05-10 03:28 UTC
## Summary

The notifications switch not working properly.

[Optional:]

OS: Windows 11
Browser: Chrome 101/ Firefox 100
Other extensions that might affect JShelter behaviour: No, I have disabled all other extensions

## How to reproduce

1. Open JShelter global settings
2. toggle notifications switch

## Expected result

Notifications are correctly switched ON or OFF.

## Actual result

Chrome: set notifications switch to ON, no notifications.
Firefox: set notifications switch to OFF, notifications always(still) show up

## Reproducibility

Yes

## Workarounds

[Have you tried tweaking the extension, e.g. JS Shield (see the setup section above). Please try to chage settings for the triggered wrappers. Were you successful?]

Yes, then No

## Have you tried other steps to solve the issue?

See above.

[Was there any progress?]

No

**Comment by polcak** [comment] 2022-05-13 08:53
Hello, thank you for your report. Can you provide more information, please be specific.

I cannot reproduce the issue using JShelter 0.10 on Firefox:

1. Open global settings.
2. Set Fingerprint Detector Behaviour to notifications.
3. Visit https://ib.moneta.cz.
4. I see a notification about detected fingerprinting attempt.
5. Go back to global settings.
6. Set Fingerprint Detector Behaviour to color.
3. Visit https://ib.moneta.cz.
4. I do not see any notification but I see red background in the badge icon.

Please provide instructions like this how to reproduce the issue.

**Comment by HUMORCE** [comment] 2022-05-13 11:49
I have confused `Network Boundary Shield > Notifications` and `Fingerprint Detector > Behavior`, but notifications never show in Chrome.

So, the notifications always show when `Fingerprint Detector > Behavior` set to `Limited|Full Blocking` is expected behavior?

Notification and (default)Behavior should be 2 options, IMO

**Comment by polcak** [comment] 2022-05-13 12:21
0.11 will provide the possibility to select active/passive FPD and notifications independently:

https://pagure.io/JShelter/webextension/c/93154d51ccbf9726d328c88a84f1c552a97bc05d?branch=devel0.11

I do not know what do you mean by "but notifications never show in Chrome". Please see https://jshelter.org/nbs/, https://jshelter.org/fpd/ and https://jshelter.org/faq/. I think that you mean that you did not see any NBS notification. That is quite normal and expected, see https://jshelter.org/localportscanning/ for an example of attack that NBS tries to protect.

I will close the issue but if you have further questions, let us know.

**Closed by polcak** 2022-05-13 12:21 UTC
Labels: question, cannot reproduce
