### ISSUE TITLE
reCaptcha fails with jsrestrictor in Firefox

### ISSUE THREAD

**Issue by mcloaked** [polcak/jsrestrictor#161] opened 2021-12-20 15:59 UTC
With jsrestrictor enabled reCaptcha fails -  illustrating this is on this page:

https://www.google.com/recaptcha/api2/demo

If you click the "I'm not a robot box" - it spins for a while and then times out without doing the reCaptcha request for input. No pop-up with a set of images to click select all with a particular feature. On the other hand if I open the same page in a Private Window in Firefox it works just fine.  Also in chrome it also works just fine.

This happens not only in the current version firefox 95.0.2-1 in arch linux but in earlier previous versions also.

Going to the jsrestrictor icon and Turning Wrappers off selected and reloading the page, allows the reCaptcha to work normally again.

The clue that led me to this was that in Firefox opening the browser console, and trying the reCaptcha again gave error messages including:

Error: TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS" was already initialized ExtensionTelemetry.jsm:109:31
    _wrappedStopwatchMethod resource://gre/modules/ExtensionTelemetry.jsm:109
    stopwatchStart resource://gre/modules/ExtensionTelemetry.jsm:70
    inject resource://gre/modules/ExtensionContent.jsm:568
    AsyncFunctionNext self-hosted:695
    sendSyncMessage moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/nscl/common/SyncMessage.js:242
    <anonymous> moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/document_start.js:59
    inject resource://gre/modules/ExtensionContent.jsm:574
    AsyncFunctionNext self-hosted:695

Error: TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID" was already initialized ExtensionTelemetry.jsm:113:41
    _wrappedStopwatchMethod resource://gre/modules/ExtensionTelemetry.jsm:113
    stopwatchStart resource://gre/modules/ExtensionTelemetry.jsm:70
    inject resource://gre/modules/ExtensionContent.jsm:568
    AsyncFunctionNext self-hosted:695
    sendSyncMessage moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/nscl/common/SyncMessage.js:242
    <anonymous> moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/document_start.js:59
    inject resource://gre/modules/ExtensionContent.jsm:574
    AsyncFunctionNext self-hosted:695
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "" ExtensionTelemetry.jsm:109:31
    _wrappedStopwatchMethod resource://gre/modules/ExtensionTelemetry.jsm:109
    stopwatchFinish resource://gre/modules/ExtensionTelemetry.jsm:74
    inject resource://gre/modules/ExtensionContent.jsm:587
    AsyncFunctionNext self-hosted:695
    sendSyncMessage moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/nscl/common/SyncMessage.js:242
    <anonymous> moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/document_start.js:59
    inject resource://gre/modules/ExtensionContent.jsm:574
    AsyncFunctionNext self-hosted:695
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID", key: "jsr@javascriptrestrictor" ExtensionTelemetry.jsm:113:41
    _wrappedStopwatchMethod resource://gre/modules/ExtensionTelemetry.jsm:113
    stopwatchFinish resource://gre/modules/ExtensionTelemetry.jsm:74
    inject resource://gre/modules/ExtensionContent.jsm:587
    AsyncFunctionNext self-hosted:695
    sendSyncMessage moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/nscl/common/SyncMessage.js:242
    <anonymous> moz-extension://a6710e37-ed9a-4e30-8e75-712d0cb15eb8/document_start.js:59
    inject resource://gre/modules/ExtensionContent.jsm:574
    AsyncFunctionNext self-hosted:695
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "" ExtensionTelemetry.jsm:109:31
    _wrappedStopwatchMethod resource://gre/modules/ExtensionTelemetry.jsm:109
    stopwatchFinish resource://gre/modules/ExtensionTelemetry.jsm:74
    inject resource://gre/modules/ExtensionContent.jsm:587
    AsyncFunctionNext self-hosted:695
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID", key: "jsr@javascriptrestrictor"

In addition I could not login to github unless I went to a Private Browsing window also!  So it looks like the extension was also preventing me from logging in to write this issue report!

**Comment by mcloaked** [comment] 2021-12-20 16:07
I did manage subsequently to login to github with the default jsrestrictor setting. So perhaps the extension is not causing an issue with github.

**Comment by polcak** [comment] 2022-01-12 12:47
Duplicate of #156

**Closed by polcak** 2022-01-12 12:47 UTC
Labels: duplicate
