### ISSUE TITLE
Content from icon is not visible

### ISSUE THREAD

**Issue by sterndata** [polcak/jsrestrictor#126] opened 2021-10-04 14:42 UTC
The width here is messed up.  [Screenshot](https://i.imgur.com/BEeZ7En.png)

**Comment by TechnologyClassroom** [comment] 2021-10-04 15:24
Can you provide some more details?  What is your browser and your browser's version?

**Comment by TechnologyClassroom** [comment] 2021-10-04 15:37
Duplicate of https://github.com/polcak/jsrestrictor/issues/112

**Comment by sterndata** [comment] 2021-10-04 15:42
Chrome / Fedora 34
Version 94.0.4606.71 (Official Build) (64-bit)

**Closed** 2021-10-05 11:37 UTC
Labels: duplicate
