### ISSUE TITLE
No protection in this test

### ISSUE THREAD

**Issue by SampeiNihira** [polcak/jsrestrictor#198] opened 2023-03-31 15:33 UTC
## Summary

https://noscriptfingerprint.com

In the test website above, JShelter, **recommended settings,** does not prevent fingerprinting.

Windows 10 Home x64
Browser: Edge last version
JShelter Version: 0.11.4

**Comment by TechnologyClassroom** [comment] 2023-03-31 16:06
JShelter specifically  targets JavaScript fingerprinting. This test specifically does not target JavaScript fingerprinting.

One critical piece missing from this test is that the fingerprint does compare how unique you are compared to other testers. It probably cannot provide this additional metric without JavaScript. The Tor Browser mitigates many of these factors by providing common values similar to every other Tor Browser user. The Tor Browser's default config and window size should return the same fingerprint for all users I believe.

The linked article sites these defining factors:

* HTTP headers
  * Accept
  * Accept-Language
  * Accept-Encoding
* CSS
  * Feature queries
  * Media queries
  * Fonts

Additionally the article highlights these additional defining factors that are not included in their test at this time:

* IP address
* User-agent
* HTTP headers
  * Client Hints

Tips to mitigate these:

* Use a common screen resolution.
* Use a common browser configuration.
* Use Tor Browser.
* Use a VPN or proxy.
* Use a common User-agent.
* Use common HTTP headers.
* Use common fonts.

Open to ideas of ways to prevent more types of fingerprinting with JShelter. IP address and User-agent are out-of-scope for JShelter as other solutions exist. Many of the other items are set in the browser configuration.

**Comment by polcak** [comment] 2023-04-03 11:39
This is in essence a duplicate of https://pagure.io/JShelter/webextension/issue/44. There is some work going in this area but as said by @TechnologyClassroom (atm) JShelter does not try to do anyting in the area of passive fingerprinting. Most importantly, because it seems hard to keep both protection in sync.

Keep watching https://pagure.io/JShelter/webextension/issue/44 if you are interested in such functionality.

**Closed by polcak** 2023-04-03 11:39 UTC
